
#ifndef CMSRepositoryErrors_h
	#define CMSRepositoryErrors_h

	#include "catralibraries/Error.h"
	#include <iostream>

	enum CMSRepositoryErrorsCodes {

		// CMSRepository
		CMSREP_CMSREPOSITORY_INIT_FAILED,
		CMSREP_CMSREPOSITORY_FINISH_FAILED,
		CMSREP_CMSREPOSITORY_CREATINGDIRSUSINGTERRITORIES_FAILED,
		CMSREP_CMSREPOSITORY_REFRESHPARTITIONSFREESIZES_FAILED,
		CMSREP_CMSREPOSITORY_SANITYCHECK_CONTENTSONFILESYSTEM_FAILED,
		CMSREP_CMSREPOSITORY_SANITYCHECK_CUSTOMERSDIRECTORY_FAILED,
		CMSREP_CMSREPOSITORY_SANITYCHECK_CONTENTSDIRECTORY_FAILED,
		CMSREP_CMSREPOSITORY_SANITYCHECK_RUNONCONTENTSINFO_FAILED,
		CMSREP_CMSREPOSITORY_GETCMSASSETPATHNAME_FAILED,
		CMSREP_CMSREPOSITORY_GETDOWNLOADLINKPATHNAME_FAILED,
		CMSREP_CMSREPOSITORY_GETSTREAMINGLINKPATHNAME_FAILED,
		CMSREP_CMSREPOSITORY_GETSTAGINGASSETPATHNAME_FAILED,
		CMSREP_CMSREPOSITORY_GETENCODINGPROFILEPATHNAME_FAILED,
		CMSREP_CMSREPOSITORY_GETIMAGEENCODINGPROFILETPATHNAME_FAILED,
		CMS_CMSREPOSITORY_GETFFMPEGENCODINGPROFILETPATHNAME_FAILED,
		CMSREP_CMSREPOSITORY_MOVEASSETINCMSREPOSITORY_FAILED,
		CMSREP_CMSREPOSITORY_MOVECONTENTINREPOSITORY_FAILED,
		CMSREP_CMSREPOSITORY_COPYFILEINREPOSITORY_FAILED,
		CMSREP_CMSREPOSITORY_GETCUSTOMERSTORAGEUSAGE_FAILED,
		CMSREP_CMSREPOSITORY_READSANITYCHECKLASTPROCESSEDCONTENT_FAILED,
		CMSREP_CMSREPOSITORY_SAVESANITYCHECKLASTPROCESSEDCONTENT_FAILED,
		CMSREP_CMSREPOSITORY_SANITYCHECKFILESYSTEMDBNOTCONSISTENT,
		CMSREP_CMSREPOSITORY_REACHEDMAXNUMBERTOBEPROCESSED,
		CMSREP_CMSREPOSITORY_NOCMSPARTITIONFOUND,
		CMSREP_CMSREPOSITORY_NOMORESPACEINCMSPARTITIONS,
		CMSREP_CMSREPOSITORY_SANITYCHECKUNEXPECTEDFILE,
		CMSREP_CMSREPOSITORY_SANITYCHECKUNEXPECTEDDIRECTORY,
		CMSREP_CMSREPOSITORY_SANITYCHECKFILETOOBIGTOBEREMOVED,
		CMSREP_CMSREPOSITORY_WRONGDIRECTORYENTRYTYPE,
		CMSREP_CMSREPOSITORY_BUFFERNOTENOUGHBIG,
		CMSREP_CMSREPOSITORY_UNEXPECTEDFILEINSTAGING,

		// Customer
		CMSREP_CUSTOMER_COPYFROM_FAILED,
		CMSREP_HASHMAP_INSERTWITHOUTDUPLICATION_FAILED,

		// libxml2
		CMSREP_LIBXML2_XMLPARSEMEMORY_FAILED,
		CMSREP_LIBXML2_XMLDOCROOTELEMENT_FAILED,
		CMSREP_XMLWRONG,
		CMSREP_XMLPARAMETERUNKNOWN,

		// common
		CMSREP_ACTIVATION_WRONG,
		CMSREP_SSCANF_FAILED,
		CMSREP_NEW_FAILED,
		CMSREP_SERVLETFAILED,

		CMSREP_MAXERRORS
	} ;

	#ifdef WIN32
		// warning C4267: 'argument' : conversion from 'size_t' to 'long',
		// possible loss of data

		#pragma warning (disable : 4267)
	#endif

	// declaration of class error
	dclCustomErrorClass (CMSRepositoryErrors, CMSREP_MAXERRORS)
   
#endif

