#!/bin/bash


sed "s/__title__/\\\\\"FF.SS.\\\\\" - Cioè: \\\\\"...che mi hai portato a fare sopra a Posillipo se non mi vuoi più bene?\\\\\"/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/ostr2\/podcastcdn\/teche_root\/YT_ITALIA_TECHE_HD\/apPpPlussg9ixfqQpssSlashTcg8veDTNGgeeqqEEqualeeqqEEqual_,1200,1800,2400\/playlist.m3u8?auth=daEagcmcgcUbZbzd1cedBdcb4acd1bFaqb1-bJ7kj4-c0-GltwxGt&aifp=V001/g" | sed "s/__description__/Dopo \\\\\"Il Pap'occhio\\\\\" Arbore torna sugli schermi con uno zibaldone di musica e comicità./g" | sed "s/__year__/1983/g" | sed "s/__categories__/\"Commedia\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h50m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/18 regali/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/ostr9\/podcastcdn\/teche_root\/YT_ITALIA_TECHE_HD_multiaudio\/54riZTgkv5NOzrk5HfvXQweeqqEEqualeeqqEEqual_,1200,1800,2400\/playlist.m3u8?auth=daEd1cDawbGchbfbycUbUckbqbWdDavaYdS-bJ7kpV-c0-DlAutFp&aifp=V001/g" | sed "s/__description__/2001: Elisa e Alessio aspettano una bambina che si chiamerà Anna, ma la futura madre scopre di avere un tumore che non le permetterà di sopravvivere alla nascita della figlia. Sconvolta, sale in auto e guida sotto una fitta pioggia. In quel preciso istante accade un salto nel tempo, nel 2019: Anna litiga con il padre nel giorno del suo 18esimo compleanno e scappa da casa; viene investita da Elisa che la soccorre e l'accoglie in casa sua./g" | sed "s/__year__/2020/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h51m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/19 stormo bombardieri/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/dom7\/podcastcdn\/teche_root\/PLAYRAI_TECHE_CINEMA_SD_3\/10018450_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEaqcqaKcEawbhcHbTcPbBcGdybQaKc9dA-bJ7krr-c0-GlxuxGn&aifp=V001/g" | sed "s/__description__/Il maggiore Davis, dopo aver dimostrato la precisione delle strategie di bombardamento ad alta quota, addestra reclute per la battaglia./g" | sed "s/__year__/1943/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h40m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/2 mattacchioni al Moulin Rouge/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/ostr1\/podcastcdn\/teche_root\/YT_ITALIA_TECHE_HD\/TKbDraMYBpPpPlussPd8b8ff2lvtAeeqqEEqualeeqqEEqual_,1200,1800,2400\/playlist.m3u8?auth=daEa9a9c.dtdadwcKaVafa.cndbcid9dscz-bJ7kAn-c0-BjswtHw&aifp=V001/g" | sed "s/__description__/Dopo un omicidio perpetrato in un night club le indagini si tramutano in una serie di buffe peripezie. Musicarello ante litteram con talenti dei primi anni 60./g" | sed "s/__year__/1964/g" | sed "s/__categories__/\"Commedia\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h16m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/2061: Un anno eccezionale/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/dom2\/podcastcdn\/teche_root\/PLAYRAI_TECHE_CINEMA_HD_2\/7311903_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEaEayaUa0c_agcndncAdbaFduaVa1dmbB-bJ7kCj-c0-AjvuxEp&aifp=V001/g" | sed "s/__description__/Nel 2061 il mondo è piombato in un oscuro medioevo a causa di una terribile crisi energetica. Un gruppo di prodi attraversa l'Italia ormai divisa cercando di recuperarne l'unità./g" | sed "s/__year__/2007/g" | sed "s/__categories__/\"Commedia\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h42m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/2night/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/opsh1\/VOD\/teche_root\/YT_ITALIA_TECHE_HD_OLD\/VblpBryfyX0WgLPJt9UNiAeeqqEEqualeeqqEEqual_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEaMaDdCdvbUd6c4dibrcxaOb9avdwbia.-bJ7kEG-c0-IjAxzHo&aifp=V001/g" | sed "s/__description__/Due trentenni sconosciuti si incontrano in un locale trendy di Roma, si piacciono immediatamente e decidono di passare la notte insieme. Ma trovare parcheggio al quartiere Pigneto, dove lei ha casa, è praticamente impossibile, e i due sono costretti a girare in macchina per ore. Quella che doveva essere una facile avventura sessuale diventa un confronto serrato tra due caratteri molto diversi, una notte di sfide e confessioni reciproche./g" | sed "s/__year__/2016/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h12m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/30 caffè per innamorarsi/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/dom6\/podcastcdn\/teche_root\/PLAYRAI_TECHE_CINEMA_HD\/12640226_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEbvbCajdrdLc2cnbOaZcYc1bFducncdal-bJ7kHA-c0-BkzuAHu&aifp=V001/g" | sed "s/__description__/Allie Morgan coltiva il sogno di diventare un giorno reporter per il \\\\\"City Herald\\\\\". Il suo capo, Addison Rickford, decide di darle una possibilità. A causa di un indirizzo sbagliato, Allie si imbatte in Sam, giovane titolare del bar \\\\\"Brimming with Love\\\\\". Allie scopre che, dopo tanti anni di caffè, Sam è arrivato alla conclusione che ai suoi clienti single ne servano al massimo 30 per conoscere qualcuno ed innamorarsi. Il suo bar è, insomma, una specie di agenzia di incontri per single in cerca dell'anima gemella. /g" | sed "s/__year__/2010/g" | sed "s/__categories__/\"Romantico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h13m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/32 dicembre/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/opsh1\/VOD\/teche_root\/YT_ITALIA_TECHE_HD_OLD\/ZIQJTuDukg3dfDr8eih3IweeqqEEqualeeqqEEqual_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEawaRcGcXbjbbbqa6dGcvdfd3cPdpa9dh-bJ7kLw-c0-CjuwtGw&aifp=V001/g" | sed "s/__description__/Tre episodi sulla relatività del tempo: una borghese assume due comparse per compiacere il marito filosofo; due anziani rivendicano il loro diritto all'amore; un disoccupato festeggia Capodanno in ritardo./g" | sed "s/__year__/1988/g" | sed "s/__categories__/\"Commedia\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h39m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/5 è il numero perfetto/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/ostr9\/podcastcdn\/teche_root\/YT_ITALIA_TECHE_HD_multiaudio\/15141851_,1200,1800,2400\/playlist.m3u8?auth=daEdpbOcPcSd0dKaVdxdYaPdzbxdIcLccaC-bJ7ptK-c0-FkrwsGr&aifp=V001/g" | sed "s/__description__/Napoli, anni Settanta. Peppino Lo Cicero, killer della camorra ormai in pensione, è orgoglioso della carriera che il figlio sta intraprendendo nella gerarchia criminale. Quando questi viene freddato in un agguato, la vendetta è l'unica strada possibile per un uomo d'onore. Si rivolge così a Totò, suo vecchio amico, guappo come lui, e a Rita, la donna che lo ama e aspetta da vent'anni. Peppino dovrà essere più feroce e abile dei suoi nemici per salvare la vita propria e delle persone che ama./g" | sed "s/__year__/2019/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h43m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/7 Minuti/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/ostr9\/podcastcdn\/teche_root\/YT_ITALIA_TECHE_HD_multiaudio\/14457708_,1200,1800,2400\/playlist.m3u8?auth=daEbhdhbedmc4dxb8afazaNcvdxchdabzbX-bJ7pvp-c0-HmyvvHp&aifp=V001/g" | sed "s/__description__/Un'azienda tessile viene acquisita da una multinazionale estera. La nuova proprietà sembra intenzionata a non effettuare licenziamenti, ma chiede alle operaie di firmare una particolare clausola che prevede la riduzione di 7 minuti dell'orario di pranzo. Lo sviluppo del dibattito fra le operaie porterà ognuna di esse a una fase di profonda riflessione./g" | sed "s/__year__/2016/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h28m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/A Beautiful Day - You Were Never Really Here/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/dom7\/podcastcdn\/teche_root\/PLAYRAI_TECHE_CINEMA_HD\/15366603_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEdKcgdQb0azbzc8bvckdnbSaNd0cwdca5-bJ7pwH-c0-GlxxtFp&aifp=V001/g" | sed "s/__description__/Joe è un veterano di guerra e fa il mercenario a New York per chi vuole liberarsi di nemici pericolosi ma non ne ha l'abilità o il coraggio. Il suo ultimo incarico è quello di sottrarre Nina, la figlia preadolescente di un politico locale, ad un giro di prostituzione minorile: una creatura abusata e offesa che fa da specchio al passato dell'uomo./g" | sed "s/__year__/2017/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h27m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/A casa tutti bene/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/ostr8\/podcastcdn\/teche_root\/YT_ITALIA_TECHE_HD_multiaudio\/yBNm7mtwGBJyirjdekq0fweeqqEEqualeeqqEEqual_,1200,1800,2400\/playlist.m3u8?auth=daEdSaPcddmc4dva.dpd.debwbodgd7a7cm-bJ7pyY-c0-EjswuHp&aifp=V001/g" | sed "s/__description__/In occasione delle nozze d'argento, Alba e Pietro riuniscono, sull'isola dove si sono ormai ritirati, tutta la famiglia per un pranzo nella loro villa. A causa del maltempo gli invitati sono costretti a trattenersi e a convivere sotto lo stesso tetto più del previsto./g" | sed "s/__year__/2018/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h44m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/A Ciambra/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/opsh1\/VOD\/teche_root\/YT_ITALIA_TECHE_HD_OLD\/hyWOgKssSlashvlpGYp5HiZGxM7weeqqEEqualeeqqEEqual_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEcYdAabc7daa5cdc2cLb7c9a.dfbBatcC-bJ7ru9-c0-AmxusGw&aifp=V001/g" | sed "s/__description__/Pio ha 14 anni e vive in Calabria nella piccola comunità Rom chiamata A Ciambra. Pio beve, fuma e frequenta persone di varie etnie: gli italiani, gli africani e i suoi consanguinei Rom. Il ragazzo segue e ammira il fratello maggiore Cosimo e da lui apprende gli elementi basilari del furto. Quando Cosimo e il padre vengono arrestati, Pio diventa il capofamiglia che deve provvedere al sostentamento della numerosa famiglia./g" | sed "s/__year__/2017/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h53m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/A ciascuno il suo/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/dom6\/podcastcdn\/teche_root\/PLAYRAI_TECHE_CINEMA_HD\/14704304_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEblcvd9b1baa0cKcPapcQcocJaXdqc4d1-bJ7rxf-c0-BlsxsFq&aifp=V001/g" | sed "s/__description__/Nella Sicilia anni Sessanta un professore di liceo cerca la verità dietro a un duplice omicidio compiuto a Cefalù. Dal romanzo omonimo di Leonardo Sciascia, selezione Premio Strega 1966. Tre Nastri d'Argento 1968./g" | sed "s/__year__/1967/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h30m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/A Hong Kong è già domani/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/dom6\/podcastcdn\/teche_root\/PLAYRAI_TECHE_CINEMA_HD\/14791637_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEdlbRbtdgcNatcXb8bvduaRaUcsd1cObo-bJ7rBA-c0-BkuvAHt&aifp=V001/g" | sed "s/__description__/Ruby è una giovane cinese-americana di Los Angeles che si occupa della progettazione di giocattoli. A Hong Kong, per motivi di lavoro, la ragazza finisce per perdersi. Casualmente incontra Josh, un americano che vive nella metropoli asiatica e che le fa conoscere la città. I due camminano nella notte e si ritrovano a chiacchierare, attratti l'uno dall'altra, ma una rivelazione comprometterà il loro rapporto./g" | sed "s/__year__/2017/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h16m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/A mano disarmata/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/ostr9\/podcastcdn\/teche_root\/YT_ITALIA_TECHE_HD_multiaudio\/14697453_,1200,1800,2400\/playlist.m3u8?auth=daEc1cFcNd6cxagcqbjaDd2czcdc5a.cwah-bJ7rDL-c0-DlswAHv&aifp=V001/g" | sed "s/__description__/Durante un lavoro d'inchiesta sul litorale romano di Ostia, la giornalista Federica Angeli si ritrova faccia a faccia con un pericoloso boss mafioso che la minaccia di morte se non rinuncerà a pubblicare l'articolo. Pochi giorni dopo l'accaduto, Federica sarà inoltre testimone oculare di una sparatoria tra clan in lotta per il dominio della zona. Nonostante sia spaventata dalle ripercussioni sulla sua famiglia e nonostante il tentativo di tutti di farla desistere, lei denuncerà i fatti. /g" | sed "s/__year__/2019/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h43m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/A Napoli non piove mai/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/ostr9\/podcastcdn\/teche_root\/YT_ITALIA_TECHE_HD_multiaudio\/14525920_,1200,1800,2400\/playlist.m3u8?auth=daEaxciata4cAbZbvdJdOc_aedTcybTa2cN-bJ7rFu-c0-DlzuAEt&aifp=V001/g" | sed "s/__description__/Barnaba, Sonia e Jacopo, tre personaggi problematici, s'incontrano per caso davanti a un San Sebastiano da restaurare in una chiesetta di Napoli. Da qui partirà il loro riscatto. La città è il quarto personaggio della storia./g" | sed "s/__year__/2015/g" | sed "s/__categories__/\"Commedia\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h37m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/A propos de Nice/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/dom7\/podcastcdn\/teche_root\/PLAYRAI_TECHE_CINEMA_HD\/15430901_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEcEapboaYaLbFdxaOaNc8dzbacJa2b3d2-bJ7rHd-c0-AjwvvEn&aifp=V001/g" | sed "s/__description__/Il ritratto di una città diventa un saggio politico rivoluzionario. Nel marzo del 1930 Vigo e Boris Kaufman (il fratello di Dziga Vertov) girano 4000 metri di pellicola, definendo il film \\\\\"punto di vista documentato, un pamphlet satirico di rara invenzione visiva\\\\\". Versione restaurata nel 2017./g" | sed "s/__year__/1930/g" | sed "s/__categories__/\"Documentario\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/23m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/A qualsiasi prezzo (1968)/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/dom6\/podcastcdn\/teche_root\/PLAYRAI_TECHE_CINEMA_HD\/14832228_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEcmcedAd5cUa1aWavcvc5aIcCbxd1dFao-bJ7rJq-c0-ClvxxHu&aifp=V001/g" | sed "s/__description__/Il professor Cummings, insigne studioso di reperti custoditi dal Vaticano, mette a punto un diabolico piano per il furto del preziosissimo tesoro di San Pietro. Ma le cose non vanno per il verso giusto./g" | sed "s/__year__/1968/g" | sed "s/__categories__/\"Giallo\", \"Thriller\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/1h38m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream

sed "s/__title__/A river called Titas/g" ./utility/movie_2_addStreamTemplate.json | sed "s/__url__/https:\/\/b70cb04c54ab478189e9d8ee45637b13.msvdn.net\/dom7\/podcastcdn\/teche_root\/PLAYRAI_TECHE_CINEMA_HD\/12196770_,1200,1800,2400,.mp4.csmil\/playlist.m3u8?auth=daEawcxalcSbbdXcsa7aEbfcfchbTb5cad7-bJ7rK5-c0-CluusGr&aifp=V001/g" | sed "s/__description__/Ispirato al celebre romanzo bengalese di Advaita Barman, il film racconta la storia epica di un fiume e delle popolazioni di pescatori che lo abitano, una dura ed appassionata elegia su una cultura che scompare./g" | sed "s/__year__/1973/g" | sed "s/__categories__/\"Drammatico\"/g" | sed "s/__language__/Italiano/g" | sed "s/__duration__/2h33m/g" > ./outputAddStream.json
curl -k -u 1:HNVOoVhHx0yoWNIxFu-ThBA1vAPEKWsxneGgze6eoddEv9aB1xp9NzsBKDBDMEFN -d @./outputAddStream.json -H "Content-Type: application/json" https://mms-api.cibortv-mms.com/catramms/1.0.1/conf/stream
